// Package drivers is a small, read-only knowledge base mapping a printer's
// reported make and model to the driver package it needs. It only reports —
// it never installs anything, runs a shell, or asks for a password. Turning
// a recommendation into an installed driver is the user's decision and the
// user's command.
package drivers

import (
	_ "embed"
	"encoding/json"
	"strings"
)

// Info describes a driver recommendation for a known printer model.
type Info struct {
	Vendor      string
	Model       string
	Package     string
	Source      string // "arch-repo", "AUR", "vendor"
	InstallHint string // shown, never run
}

// database holds two kinds of entry: a handful checked one at a time for a
// specific AUR or vendor package, and the bulk loaded below from gutenprint's
// own printer list — verified by construction, since gutenprint really does
// drive every model it names. A wrong recommendation is worse than none, so
// nothing here is guessed from a vendor's product line.
var database = []Info{
	{
		Vendor:      "Epson",
		Model:       "L3150",
		Package:     "epson-inkjet-printer-escpr",
		Source:      "AUR",
		InstallHint: "yay -S epson-inkjet-printer-escpr",
	},
}

//go:embed gutenprint.json
var gutenprintJSON []byte

// gutenprintModel is one entry of gutenprint.json, generated by
// scripts/gen-driverdb.py from gutenprint's escp2/canon/pcl printer family
// XML (gutenprint 5.3.5-1). Installing the single "gutenprint" package is
// enough for cupsd to list every one of these: it ships its own CUPS driver
// executable (/usr/lib/cups/driver/gutenprint.5.3) that answers lpinfo -m
// dynamically, no separate PPD package needed.
type gutenprintModel struct {
	Vendor string `json:"vendor"`
	Model  string `json:"model"`
}

func init() {
	var models []gutenprintModel
	if err := json.Unmarshal(gutenprintJSON, &models); err != nil {
		panic("drivers: malformed gutenprint.json: " + err.Error())
	}
	for _, m := range models {
		database = append(database, Info{
			Vendor:      m.Vendor,
			Model:       m.Model,
			Package:     "gutenprint",
			Source:      "arch-repo",
			InstallHint: "pacman -S gutenprint",
		})
	}
}

// unresolvable is what CUPS reports when it has nothing useful to say about a
// printer's make — matching against these would be a guess, not a lookup.
// Mirrors the exclusion list internal/cups uses for the same reason.
var unresolvable = map[string]bool{
	"unknown": true,
	"generic": true,
	"local":   true,
	"raw":     true,
}

// Resolve looks up a known driver for a make-and-model string such as
// "EPSON L3150 Series". ok is false when there is no confident match, which
// is preferable to recommending the wrong driver.
//
// Among every entry whose vendor and model words all appear in makeModel,
// the one with the most words wins: "Epson Stylus Photo" and "Epson Stylus
// Photo R280" both match "Epson Stylus Photo R280 Series", and the second,
// more specific one is the real answer.
func Resolve(makeModel string) (Info, bool) {
	words := normalize(makeModel)
	if len(words) == 0 || unresolvable[words[0]] {
		return Info{}, false
	}

	present := make(map[string]bool, len(words))
	for _, w := range words {
		present[w] = true
	}

	best := -1
	var match Info
	for _, entry := range database {
		vendorWords, modelWords := normalize(entry.Vendor), normalize(entry.Model)
		if !containsAll(present, vendorWords) || !containsAll(present, modelWords) {
			continue
		}
		if specificity := len(vendorWords) + len(modelWords); specificity > best {
			best, match = specificity, entry
		}
	}
	return match, best >= 0
}

func containsAll(present map[string]bool, words []string) bool {
	if len(words) == 0 {
		return false
	}
	for _, w := range words {
		if !present[w] {
			return false
		}
	}
	return true
}

// normalize lowercases and splits into words. A match only requires every
// vendor and model word to be present somewhere in the input, so case,
// spacing, word order and extra words CUPS adds — "Series", for one — are
// already harmless without needing special-casing here.
func normalize(s string) []string {
	return strings.Fields(strings.ToLower(s))
}
